### ISSUE TITLE
How should module objects be declared?

### ISSUE THREAD

**Issue by darlanalves** [darlanalves/angular-di-annotations#1]
The library is just generating some calls to a hypothetical `$module` object that would be our application module.

What would be better:
- declare the module name on each file via annotations and inject to this module?
- use a convention like `$module` as a global variable to inject the AngularJS stuff?
- make this a configuration?

**Comment by kkogovsek** [comment]
I'm with first one: declare the module name on each file via annotations and inject to this module;

Let's keep things simple enough. You should consider first building the modules and then later on controllers, configs, etc. Some of boilerplates does everything as on FS and it comes out as bad as no module defined. You should consider that some of us split our module in different files.

**Comment by darlanalves** [comment]
@kkogovsek I do consider that. Actually that's the main reason I can't decide which one to use, because I use several files per module too.

One thing I was wondering is to have a `module.js` file only with a comment inside to declare the module and maybe some config or run blocks to initialize that module, also annotated. Then, a Gulp task could execute this lib on every JS file inside a module, starting by `module.js`. After injecting the module syntax, the files could be handled to another task, like `gulp-wrap`, to enclosure the resulting code into IIFE blocks, or even `gulp-concat` before it, to join all the files, and then generate a final `my.module.js` file with all the code required to run a given module.

That was my first though, then I started thinking about projects that have multiple levels of folders or have only one module and maybe a global variable that points to the application module. Thing is, there is no single convention on how to write an app, there are several ways and it's a bit hard to handle all the cases without bloating the library =/
